services:
  - type: web
    name: portfolio
    env: static
    buildCommand: ""        # no build step needed for static HTML
    staticPublishPath: "/"  # serve files from root directory
    plan: free
